version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: real-redis
    ports:
      - "6379:6379"
    # 启动 Redis 时配置慢查询阈值为 10000 微秒 (10毫秒)，保留最近 128 条日志
    command: redis-server --slowlog-log-slower-than 10000 --slowlog-max-len 128
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-client-go
    depends_on:
      redis:
        condition: service_healthy
